apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata: # Dictionary
        name: myapp2-pod-in
        labels: # Dictionary 
          app: myapp2         
    spec:
        containers: # List
          - name: myapp2-container
            image: stacksimplify/kubenginx:2.0.0
            ports:
              - containerPort: 80
