apiVersion: v1
kind: Service
metadata:
  name:  myapp-pod-nodeport-service  # Name of the Service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: <Port>
    targetPort: <Target Port>
