apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nginxapp
  labels:
    app: frontend-nginxapp
    tier: frontend
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: frontend-nginxapp
      tier: frontend
    spec:
      containers:
        