apiVersion: v1
kind: service
metadata:
  name: my-backed-service
  labels:
    app: backend-restapp
    tier: backend
spec:
  #type: ClusterIP is a default service 
  selector: 
    app: backend-restapp
  ports:
    - name: http
      port: 8080
      targetPort: 8080