apiVersion: v1
kind: Service
metadata:
  - name: my-frontend-nodeport-service
    labels:
      app: frontend-nginxapp
      tier: frontend
spec: 
  type: NodePort
  selector:
    app: frontend-nginxapp
  ports:
    - name: http
      port: 80
      targetPort: 80
      NodePort: 31234
  